### ISSUE TITLE
Mother Earth Radio 1.2.2 and Bookworm wont do  

### ISSUE THREAD

**Issue by FlorianReiterer** [volumio/volumio-plugins-sources-bookworm#1]
Unfortunately i wont be able to get my MER plugin upgraded in a timely fashion, due to my poor python knowledge.
Plugin in its current 1.2.2 would install and be functional, but has very old dependencies going. If i add the needed dependeny checks in package.json, it wont install (of course)
I cannot even make out where these libraries are called from (inflight, glob etc.) so i will have to get help from a python-eer somehow and try to make this work. 
I do my best, it would be a shame to loose volumio plugin!

If somebody has a hint for me i`d be eternally grateful for directions how to update my code. 
https://github.com/FlorianReiterer/volumio-plugins-sources/tree/master/motherearthradio
which is in essence marco79cgn's radioparadise code that i adapted.

**Comment by FlorianReiterer** [comment]
Thank you, you are right, package.json like this:
https://github.com/FlorianReiterer/volumio-plugins-sources/blob/master/motherearthradio/package.json
works fine! Had to change the "engines" "node" to ">=14.5.4." though.
How do you want it to be added to rep, because the volumio plugin submit fails with "OS "bookworm" not supported" in the build i made me from staurday. Can i copy from one repo to my forked repo and pull request it? Or what do you want me to do, thank you.

**Comment by balbuze** [comment]
Perfect!
You have to submit from a bookworm version v0.0.12
If not possible, send a PR in the dedicated bookworm plugin repo. I'll submit it!
Thanks a lot!

**Comment by balbuze** [comment]
Hello! Send a PR on this repo for your plugin!
TY

**Comment by FlorianReiterer** [comment]
i'm on it....struggling with building a proper volumio build, but i expect PR tonight.

**Comment by FlorianReiterer** [comment]
Ha! Thanks!
