### ISSUE TITLE
Touch Display unmet dependency on 0.013 - libglx-mesa0

### ISSUE THREAD

**Issue by foonerd** [volumio/volumio-plugins-sources-bookworm#26]
@gvolt 

Whilst testing newest Bookworm 0.013 build the touch_display errors:

The following packages have unmet dependencies:
libglx-mesa0 : Depends: libglapi-mesa (= 23.2.1-1~bpo12+rpt3) but 24.2.4-1~bpo12+1~rpt1 is to be installed
Depends: libgl1-mesa-dri but it is not going to be installed
Installation of x11-utils failed

I can see some changes from x11 upstream. Is it something you can check from your end?

**Comment by gvolt** [comment]
I'll check it out, but I might not be able to make it this weekend.

**Comment by gvolt** [comment]
Just set up a new system running 0.022. Installing version 3.5.2 of the plugin now works.

**Comment by foonerd** [comment]
Please take a look at issue here: https://github.com/volumio/volumio-os/issues/45
Closed with PR: https://github.com/volumio/volumio-os/pull/49
Since we are using "untested" repo, the situation will require frequent verification, should deb moved to main.
