### ISSUE TITLE
"volumio plugin submit" fails

### ISSUE THREAD

**Issue by gvolt** [volumio/volumio-plugins-sources-bookworm#4]
After creating the PR for the Touch Display plugin I tried to submit the plugin from a system running Volumio 0.011, but executing `volumio plugin submit` failed with

`Invalid os: bookworm. Valid values: "buster"`

**Comment by balbuze** [comment]
Hello,
You have to update to v0.0.12 to submit.
![share_5478175736400681135.png](https://github.com/user-attachments/assets/c3d9d16f-3a56-4975-9617-24f249ab56eb)

TY

**Comment by gvolt** [comment]
I haven't seen this information anywhere, so thank you very much!

"And i386 can be removed from package.json": There is no "i386" in package.json, but just "armhf" - or have I misunderstood?

**Comment by balbuze** [comment]
Sorry, I mixed with an other plugin...
All perfect. I tested tonight 
TY

**Comment by gvolt** [comment]
Thanks for the clarification. I just submitted the Touch Display plugin according to PR #3.
